---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ex2
  namespace: ex2
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/kingdonb/github-actions-demo

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ex2
  namespace: ex2
spec:
  interval: 1m0s
  timeout: 15s
  dependsOn:
    - name: flux-system
      namespace: flux-system
  path: ./apps/podinfo/ex2-naive-test-semver-automation
  prune: true
  serviceAccountName: ex2
  sourceRef:
    kind: GitRepository
    name: ex2

