apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ex5-podinfo
spec:
  rules:
  - host: ex5-podinfo
    http:
      paths:
      - backend:
          service:
            name: podinfo
            port:
              number: 9898
        path: /
        pathType: Prefix
