---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ex6
  namespace: ex6
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/kingdonb/github-actions-demo

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ex6
  namespace: ex6
spec:
  suspend: false
  interval: 1m0s
  timeout: 15s
  dependsOn:
    - name: flux-system
      namespace: flux-system
  path: ./apps/podinfo/ex6-helmrelease-from-gitrepo-with-gitvalues
  prune: true
  serviceAccountName: ex6
  sourceRef:
    kind: GitRepository
    name: ex6

