---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ex1
  namespace: ex1
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/kingdonb/github-actions-demo

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ex1
  namespace: ex1
spec:
  interval: 1m0s
  timeout: 15s
  path: ./apps/podinfo/ex1-naive-dev-automation
  prune: true
  serviceAccountName: ex1
  sourceRef:
    kind: GitRepository
    name: ex1

