apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ex4-podinfo
spec:
  rules:
  - host: ex4-podinfo
    http:
      paths:
      - backend:
          service:
            name: frontend
            port:
              number: 80
        path: /
        pathType: Prefix
