apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: podinfo-policy
  namespace: ex1
spec:
  imageRepositoryRef:
    name: podinfo
  filterTags:
    pattern: '^.*-(?P<ts>[0-9]+)-[a-f0-9]+'
    extract: '$ts'
  policy:
    numerical:
      order: asc
