apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ex1

resources:
- gitrepo.yaml
- github.com/kingdonb/podinfo//deploy/overlays/dev
patches:
- frontend-patch.yaml
- backend-patch.yaml
- delete-namespace-patch.yaml
