apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ex1

resources:
- gitrepo.yaml
- imagerepo.yaml
- imagepolicy.yaml
- imageupdate.yaml
- flux-system-gitrepo.yaml

- github.com/kingdonb/podinfo//deploy/overlays/dev?ref=flux-gha-demo

patchesStrategicMerge:
- |-
  $patch: delete
  apiVersion: v1
  kind: Namespace
  metadata:
    name: dev

images:
  - name: ghcr.io/kingdonb/podinfo
    newName: ghcr.io/kingdonb/podinfo
    newTag: 6.0.0 # {"$imagepolicy": "ex1:dev-update:tag"}
