apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ex7
  namespace: flux-system
spec:
  suspend: false
  interval: 1m0s
  timeout: 15s
  dependsOn:
  - name: flux-system
    namespace: flux-system
  path: ./apps/podinfo/ex07-dummy
  prune: true
  serviceAccountName: ex7
  sourceRef:
    kind: GitRepository
    name: flux-system
