apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ex7
  namespace: flux-system
spec:
  interval: 1m0s
  timeout: 15s
  path: ./apps/podinfo/ex07-dummy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
