---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: ex6
spec:
  chart:
    spec:
      chart: ./charts/podinfo
      sourceRef:
        kind: GitRepository
        name: podinfo-gha-demo
      version: '>=6.0.0' # not used
  interval: 2m0s
  timeout: 1m0s
  releaseName: podinfo
  serviceAccountName: ex6
  values:
    secretName: podinfo-values # for example
  valuesFrom:
    - kind: ConfigMap
      name: podinfo-values
