apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ex6
resources:
- ingress.yaml
- helmrelease.yaml
- gitrepo.yaml
configMapGenerator:
  - name: podinfo-values
    files:
      - values.yaml=my-values.yaml
configurations:
  - kustomizeconfig.yaml
