---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 1m0s
  ref:
    semver: ${SEMVER_TAG}
  url: https://github.com/kingdonb/podinfo.git
